// Load .env.local first (secrets), then .env (defaults) — neither is committed to git
require('dotenv').config({ path: require('path').join(__dirname, '.env.local') });
require('dotenv').config(); // won't overwrite values already set by .env.local
const express = require('express');
const session = require('express-session');
const axios = require('axios');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const os = require('os');
const FitParser = require('fit-file-parser').default;

const app = express();
const PORT = process.env.PORT || 3000;

// Ensure uploads directory exists
const uploadDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}

const upload = multer({ dest: uploadDir });

// Middleware
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: false, limit: '50mb' }));
app.use(express.static(path.join(__dirname, 'public'), {
  etag: false,
  lastModified: true,
  setHeaders: (res) => {
    res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  }
}));
app.use(session({
  secret: process.env.SESSION_SECRET || 'di2va-secret',
  resave: false,
  saveUninitialized: false,
  cookie: { maxAge: 24 * 60 * 60 * 1000 } // 24 hours
}));

// ─── Setup / First-Run Configuration ────────────────────────────────────────

function isStravaConfigured() {
  return process.env.STRAVA_CLIENT_ID &&
         process.env.STRAVA_CLIENT_ID.trim() !== '' &&
         process.env.STRAVA_CLIENT_SECRET &&
         process.env.STRAVA_CLIENT_SECRET.trim() !== '';
}

// Serve setup page
app.get('/setup', (req, res) => {
  if (isStravaConfigured()) return res.redirect('/');
  res.send(getSetupPageHtml());
});

// Save credentials from setup form
app.post('/setup', express.urlencoded({ extended: false }), (req, res) => {
  const { client_id, client_secret, session_secret } = req.body;

  if (!client_id || !client_secret) {
    return res.status(400).send('Client ID and Client Secret are required.');
  }

  // Write secrets to .env.local (gitignored — never committed)
  const envLocalPath = path.join(__dirname, '.env.local');
  const envContent = [
    '# Auto-generated by setup wizard — DO NOT commit this file',
    `STRAVA_CLIENT_ID=${client_id.trim()}`,
    `STRAVA_CLIENT_SECRET=${client_secret.trim()}`,
    `SESSION_SECRET=${(session_secret || '').trim() || require('crypto').randomBytes(32).toString('hex')}`,
  ].join('\n') + '\n';

  fs.writeFileSync(envLocalPath, envContent, { mode: 0o600 }); // owner-only read/write

  // Hot-reload into current process
  process.env.STRAVA_CLIENT_ID = client_id.trim();
  process.env.STRAVA_CLIENT_SECRET = client_secret.trim();
  if (session_secret) process.env.SESSION_SECRET = session_secret.trim();

  console.log('\n✅ Strava API credentials saved to .env.local (gitignored)');
  res.redirect('/');
});

// Redirect everything to /setup when not configured (except static assets)
app.use((req, res, next) => {
  if (isStravaConfigured()) return next();
  // Allow setup routes, auth routes, and static assets through
  if (req.path === '/setup' || req.path.startsWith('/auth/') || req.path.match(/\.(css|js|ico|png|jpg|svg|woff2?)$/)) {
    return next();
  }
  res.redirect('/setup');
});

// ─── Strava OAuth ───────────────────────────────────────────────────────────

const STRAVA_AUTH_URL = 'https://www.strava.com/oauth/authorize';
const STRAVA_TOKEN_URL = 'https://www.strava.com/oauth/token';
const STRAVA_API_BASE = 'https://www.strava.com/api/v3';

app.get('/auth/strava', (req, res) => {
  const params = new URLSearchParams({
    client_id: process.env.STRAVA_CLIENT_ID,
    redirect_uri: process.env.CALLBACK_URL || `http://localhost:${PORT}/auth/strava/callback`,
    response_type: 'code',
    scope: 'read,activity:read_all',
    approval_prompt: 'auto'
  });
  res.redirect(`${STRAVA_AUTH_URL}?${params}`);
});

app.get('/auth/strava/callback', async (req, res) => {
  const { code } = req.query;
  if (!code) {
    return res.redirect('/?error=no_code');
  }

  try {
    const response = await axios.post(STRAVA_TOKEN_URL, {
      client_id: process.env.STRAVA_CLIENT_ID,
      client_secret: process.env.STRAVA_CLIENT_SECRET,
      code,
      grant_type: 'authorization_code'
    });

    req.session.strava = {
      access_token: response.data.access_token,
      refresh_token: response.data.refresh_token,
      expires_at: response.data.expires_at,
      athlete: response.data.athlete
    };

    res.redirect('/');
  } catch (err) {
    console.error('OAuth error:', err.response?.data || err.message);
    res.redirect('/?error=auth_failed');
  }
});

app.get('/auth/logout', (req, res) => {
  req.session.destroy();
  res.redirect('/');
});

// ─── Auth middleware ─────────────────────────────────────────────────────────

async function ensureValidToken(req) {
  const strava = req.session.strava;
  if (!strava) return null;

  // Refresh token if expired (or within 5 minutes of expiry)
  if (strava.expires_at < (Date.now() / 1000) + 300) {
    try {
      const response = await axios.post(STRAVA_TOKEN_URL, {
        client_id: process.env.STRAVA_CLIENT_ID,
        client_secret: process.env.STRAVA_CLIENT_SECRET,
        refresh_token: strava.refresh_token,
        grant_type: 'refresh_token'
      });
      strava.access_token = response.data.access_token;
      strava.refresh_token = response.data.refresh_token;
      strava.expires_at = response.data.expires_at;
    } catch (err) {
      console.error('Token refresh error:', err.response?.data || err.message);
      return null;
    }
  }

  return strava.access_token;
}

function stravaApi(token) {
  return axios.create({
    baseURL: STRAVA_API_BASE,
    headers: { Authorization: `Bearer ${token}` }
  });
}

// ─── API Routes ─────────────────────────────────────────────────────────────

app.get('/api/me', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });
  res.json(req.session.strava.athlete);
});

app.get('/api/activities', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const page = req.query.page || 1;
    const perPage = req.query.per_page || 30;
    const api = stravaApi(token);
    const response = await api.get('/athlete/activities', {
      params: { page, per_page: perPage }
    });

    // Filter to rides only
    const rides = response.data.filter(a => a.type === 'Ride' || a.type === 'VirtualRide');
    res.json(rides);
  } catch (err) {
    console.error('Activities error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to fetch activities' });
  }
});

app.get('/api/activity/:id', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const api = stravaApi(token);
    const response = await api.get(`/activities/${req.params.id}`);
    res.json(response.data);
  } catch (err) {
    console.error('Activity error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to fetch activity' });
  }
});

app.get('/api/activity/:id/streams', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const api = stravaApi(token);
    // Request all available stream types
    const streamTypes = [
      'time', 'latlng', 'altitude', 'distance',
      'heartrate', 'cadence', 'watts', 'temp',
      'moving', 'grade_smooth', 'velocity_smooth'
    ].join(',');

    const response = await api.get(`/activities/${req.params.id}/streams`, {
      params: { keys: streamTypes, key_type: 'distance' }
    });

    // Convert array of streams to an object keyed by type
    const streams = {};
    response.data.forEach(stream => {
      streams[stream.type] = stream.data;
    });

    res.json(streams);
  } catch (err) {
    console.error('Streams error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to fetch streams' });
  }
});

// ─── Fetch & Parse Original FIT File from Strava ────────────────────────────

app.get('/api/activity/:id/fit-gear-data', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    // Strava exposes the original uploaded file at this endpoint.
    // NOTE: This is not an official public API — it may return 403 or redirect
    // to a web login page. When it fails we fall back to gear estimation.
    console.log(`Fetching original FIT for activity ${req.params.id}...`);
    const response = await axios.get(
      `${STRAVA_API_BASE}/activities/${req.params.id}/export_original`,
      {
        headers: { Authorization: `Bearer ${token}` },
        responseType: 'arraybuffer',
        timeout: 30000,
        maxRedirects: 5
      }
    );

    const contentType = response.headers['content-type'] || '';
    const buffer = Buffer.from(response.data);
    console.log(`  Got ${buffer.length} bytes, content-type: ${contentType}`);

    // Check if we actually got a FIT file (starts with header size byte + ".FIT")
    const isFit = buffer.length > 12 &&
                  buffer.toString('ascii', 8, 12) === '.FIT';

    if (!isFit && !contentType.includes('octet-stream') && !contentType.includes('fit')) {
      return res.json({
        has_gear_data: false,
        source: 'strava_export',
        error: 'Original file is not a FIT file (may be GPX or TCX)'
      });
    }

    // Parse the FIT file
    const fitParser = new FitParser({
      force: true,
      speedUnit: 'km/h',
      lengthUnit: 'km',
      temperatureUnit: 'celsius',
      elapsedRecordField: true,
      mode: 'both'
    });

    fitParser.parse(buffer, (error, data) => {
      if (error) {
        console.error('FIT parse error (from Strava):', error);
        return res.json({
          has_gear_data: false,
          source: 'strava_export',
          error: 'Failed to parse FIT file'
        });
      }

      const result = extractDi2Data(data);
      result.source = 'strava_export';
      res.json(result);
    });

  } catch (err) {
    const status = err.response?.status;
    // 404 = no original file, 403 = not authorized for this activity
    if (status === 404 || status === 403) {
      return res.json({
        has_gear_data: false,
        source: 'strava_export',
        error: status === 404
          ? 'No original file available for this activity'
          : 'Not authorized to access original file'
      });
    }
    console.error('FIT fetch error:', status, err.message);
    console.log('  → This is expected — export_original is not an official Strava API endpoint.');
    console.log('  → For actual Di2 data, upload the .FIT file from your bike computer.');
    res.json({
      has_gear_data: false,
      source: 'strava_export',
      error: 'Failed to fetch original file from Strava'
    });
  }
});

// ─── FIT File Upload & Parsing ──────────────────────────────────────────────

app.post('/api/parse-fit', upload.single('fitfile'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file uploaded' });
  }

  const filePath = req.file.path;

  try {
    const fileBuffer = fs.readFileSync(filePath);
    const fitParser = new FitParser({
      force: true,
      speedUnit: 'km/h',
      lengthUnit: 'km',
      temperatureUnit: 'celsius',
      elapsedRecordField: true,
      mode: 'both'
    });

    fitParser.parse(fileBuffer, (error, data) => {
      // Clean up uploaded file
      fs.unlinkSync(filePath);

      if (error) {
        console.error('FIT parse error:', error);
        return res.status(400).json({ error: 'Failed to parse FIT file' });
      }

      // Extract gear shift data from events and records
      const result = extractDi2Data(data);
      res.json(result);
    });
  } catch (err) {
    // Clean up on error
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
    console.error('FIT processing error:', err);
    res.status(500).json({ error: 'Failed to process FIT file' });
  }
});

/**
 * Decode gear data packed in a FIT event's uint32 `data` field.
 * Layout: byte0 = rear_gear_num, byte1 = rear_gear_teeth,
 *         byte2 = front_gear_num, byte3 = front_gear_teeth
 */
function decodeGearData(data) {
  if (typeof data !== 'number' || data === 0) return null;
  return {
    rear_gear_num:    data & 0xFF,
    rear_gear_teeth:  (data >> 8) & 0xFF,
    front_gear_num:   (data >> 16) & 0xFF,
    front_gear_teeth: (data >> 24) & 0xFF
  };
}

/**
 * Extract Di2 gear shift data from parsed FIT file.
 * Handles rear_gear_change / front_gear_change events (Garmin)
 * and the older gear_change event type.
 */
function extractDi2Data(fitData) {
  const gearChanges = [];
  const records = [];

  // Extract gear change events — match all known event names
  if (fitData.events) {
    fitData.events.forEach(event => {
      const isGearEvent =
        event.event === 'rear_gear_change' ||
        event.event === 'front_gear_change' ||
        event.event === 'gear_change' ||
        event.event_type === 'gear_change';

      if (!isGearEvent) return;

      // Try named fields first (some parsers expand them),
      // then decode from the packed uint32 data field
      let rearNum   = event.rear_gear_num;
      let rearTeeth = event.rear_gear_teeth;
      let frontNum  = event.front_gear_num;
      let frontTeeth = event.front_gear_teeth;

      if (rearTeeth === undefined && event.data !== undefined) {
        const decoded = decodeGearData(event.data);
        if (decoded) {
          rearNum   = decoded.rear_gear_num;
          rearTeeth = decoded.rear_gear_teeth;
          frontNum  = decoded.front_gear_num;
          frontTeeth = decoded.front_gear_teeth;
        }
      }

      gearChanges.push({
        timestamp: event.timestamp,
        event_type: event.event,          // 'rear_gear_change' or 'front_gear_change'
        rear_gear_num:    rearNum   || null,
        rear_gear_teeth:  rearTeeth || null,
        front_gear_num:   frontNum  || null,
        front_gear_teeth: frontTeeth || null,
        gear_ratio: (frontTeeth && rearTeeth) ? +(frontTeeth / rearTeeth).toFixed(2) : null
      });
    });
  }

  // Sort gear changes by timestamp (they should already be, but be safe)
  gearChanges.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));

  // Extract per-record data (records have timestamps, position, gear info etc.)
  if (fitData.records) {
    fitData.records.forEach(record => {
      const rec = {
        timestamp: record.timestamp,
        elapsed_time: record.elapsed_time,
        distance: record.distance,
        position_lat: record.position_lat,
        position_long: record.position_long,
        altitude: record.altitude || record.enhanced_altitude,
        speed: record.speed || record.enhanced_speed,
        cadence: record.cadence,
        power: record.power,
        heart_rate: record.heart_rate,
        temperature: record.temperature
      };

      // Di2 specific fields that may appear directly in records
      if (record.rear_gear_num !== undefined) rec.rear_gear_num = record.rear_gear_num;
      if (record.rear_gear_teeth !== undefined) rec.rear_gear_teeth = record.rear_gear_teeth;
      if (record.front_gear_num !== undefined) rec.front_gear_num = record.front_gear_num;
      if (record.front_gear_teeth !== undefined) rec.front_gear_teeth = record.front_gear_teeth;
      if (record.left_right_balance !== undefined) rec.left_right_balance = record.left_right_balance;

      records.push(rec);
    });
  }

  // Merge gear change events into records by timestamp
  if (gearChanges.length > 0 && records.length > 0) {
    let gearIdx = 0;
    let currentGear = {
      front_gear_num:   gearChanges[0].front_gear_num,
      front_gear_teeth: gearChanges[0].front_gear_teeth,
      rear_gear_num:    gearChanges[0].rear_gear_num,
      rear_gear_teeth:  gearChanges[0].rear_gear_teeth
    };

    records.forEach(record => {
      // Advance gear index to match timestamp
      while (gearIdx < gearChanges.length &&
             new Date(gearChanges[gearIdx].timestamp) <= new Date(record.timestamp)) {
        const gc = gearChanges[gearIdx];
        // Each event carries full state (front + rear), so update all fields
        if (gc.front_gear_num)   currentGear.front_gear_num   = gc.front_gear_num;
        if (gc.front_gear_teeth) currentGear.front_gear_teeth = gc.front_gear_teeth;
        if (gc.rear_gear_num)    currentGear.rear_gear_num    = gc.rear_gear_num;
        if (gc.rear_gear_teeth)  currentGear.rear_gear_teeth  = gc.rear_gear_teeth;
        gearIdx++;
      }

      // Apply current gear to record if not already set
      if (!record.rear_gear_num)    record.rear_gear_num    = currentGear.rear_gear_num;
      if (!record.rear_gear_teeth)  record.rear_gear_teeth  = currentGear.rear_gear_teeth;
      if (!record.front_gear_num)   record.front_gear_num   = currentGear.front_gear_num;
      if (!record.front_gear_teeth) record.front_gear_teeth = currentGear.front_gear_teeth;

      // Calculate gear ratio
      if (record.front_gear_teeth && record.rear_gear_teeth) {
        record.gear_ratio = +(record.front_gear_teeth / record.rear_gear_teeth).toFixed(2);
      }
    });
  }

  // Extract device info — match Shimano by string name or known manufacturer IDs
  // (manufacturer 41 = Shimano in some FIT profiles, or appears as numeric when
  //  the parser doesn't have the enum mapping)
  const SHIMANO_MFR_IDS = [41, 'shimano'];
  const deviceInfo = fitData.device_infos || [];
  const di2Devices = deviceInfo.filter(d =>
    SHIMANO_MFR_IDS.includes(d.manufacturer) ||
    (d.product_name && d.product_name.toLowerCase().includes('di2')) ||
    (d.product_name && d.product_name.toLowerCase().includes('shimano'))
  );

  const hasGearData = gearChanges.length > 0 ||
                      records.some(r => r.rear_gear_num !== undefined);

  console.log(`  Di2 extraction: ${gearChanges.length} gear changes, ` +
              `${records.length} records, has_gear_data=${hasGearData}`);

  return {
    gear_changes: gearChanges,
    records: records,
    di2_devices: di2Devices,
    session: fitData.sessions?.[0] || null,
    has_gear_data: hasGearData
  };
}

// ─── Gear Estimation from Cadence/Speed ─────────────────────────────────────

app.post('/api/estimate-gears', express.json(), (req, res) => {
  const { cadence, velocity_smooth, distance, latlng, altitude } = req.body;

  if (!cadence || !velocity_smooth) {
    return res.status(400).json({ error: 'Cadence and speed data required' });
  }

  // Common road bike gear configurations
  const CHAINRINGS = [34, 50]; // Compact: 34/50, Standard: 39/53
  const CASSETTE = [11, 12, 13, 14, 15, 17, 19, 21, 23, 25, 28]; // 11-28 cassette
  const WHEEL_CIRCUMFERENCE = 2.105; // meters (700x25c)

  const gearData = [];

  for (let i = 0; i < cadence.length; i++) {
    const rpm = cadence[i];
    const speed = velocity_smooth[i]; // m/s

    if (rpm <= 0 || speed <= 0.5) {
      gearData.push({
        index: i,
        front: null,
        rear: null,
        gear_ratio: null,
        estimated: true
      });
      continue;
    }

    // Calculate actual gear inches from speed and cadence
    // speed (m/s) = cadence (rpm) / 60 * gear_ratio * wheel_circumference
    const actualRatio = (speed / (rpm / 60)) / WHEEL_CIRCUMFERENCE;

    // Find closest matching gear combination
    let bestMatch = null;
    let bestDiff = Infinity;

    for (const front of CHAINRINGS) {
      for (const rear of CASSETTE) {
        const ratio = front / rear;
        const diff = Math.abs(ratio - actualRatio);
        if (diff < bestDiff) {
          bestDiff = diff;
          bestMatch = { front, rear, ratio };
        }
      }
    }

    gearData.push({
      index: i,
      front: bestMatch?.front || null,
      rear: bestMatch?.rear || null,
      gear_ratio: bestMatch?.ratio?.toFixed(2) || null,
      confidence: bestDiff < 0.15 ? 'high' : bestDiff < 0.3 ? 'medium' : 'low',
      estimated: true
    });
  }

  res.json({ gears: gearData });
});

// ─── FIT Library — Auto-match FIT files to Strava activities ────────────────

/**
 * Scan a directory (recursively) for .FIT files and extract their start time
 * by parsing just the session header. Returns an array of { path, startTime }.
 *
 * Results are cached in memory and refreshed when the folder changes.
 */
let fitLibraryCache = { folder: null, files: [], scannedAt: 0 };

function getFitFolder() {
  const configured = (process.env.FIT_FOLDER || '').trim();
  if (configured) return configured;
  // Default to ~/Downloads so auto-download from Strava just works
  const downloads = path.join(os.homedir(), 'Downloads');
  return fs.existsSync(downloads) ? downloads : '';
}

function setFitFolder(folder) {
  process.env.FIT_FOLDER = folder;
  fitLibraryCache = { folder: null, files: [], scannedAt: 0 }; // invalidate

  // Persist to .env.local
  const envLocalPath = path.join(__dirname, '.env.local');
  let content = '';
  if (fs.existsSync(envLocalPath)) {
    content = fs.readFileSync(envLocalPath, 'utf8');
    // Remove existing FIT_FOLDER line
    content = content.replace(/^FIT_FOLDER=.*\n?/m, '');
  }
  content = content.trimEnd() + `\nFIT_FOLDER=${folder}\n`;
  fs.writeFileSync(envLocalPath, content, { mode: 0o600 });
}

/**
 * Recursively find all .fit/.FIT files in a directory.
 */
function findFitFiles(dir, maxDepth = 3, depth = 0) {
  if (depth > maxDepth) return [];
  const results = [];
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        results.push(...findFitFiles(fullPath, maxDepth, depth + 1));
      } else if (entry.isFile() && /\.fit$/i.test(entry.name)) {
        results.push(fullPath);
      }
    }
  } catch (err) {
    // Permission denied or missing dir — skip silently
  }
  return results;
}

/**
 * Quick-parse a FIT file to extract just the session start time.
 * Returns a Date or null.
 */
function getFitStartTime(filePath) {
  try {
    const buf = fs.readFileSync(filePath);
    // Quick sanity check for FIT header
    if (buf.length < 14 || buf.toString('ascii', 8, 12) !== '.FIT') return null;

    const parser = new FitParser({ force: true, mode: 'list' });
    let startTime = null;

    // Synchronous: parse returns via callback immediately for file buffer
    parser.parse(buf, (err, data) => {
      if (err) return;
      // Try session start_time first, then first record timestamp, then file_id time_created
      if (data.sessions?.[0]?.start_time) {
        startTime = new Date(data.sessions[0].start_time);
      } else if (data.records?.[0]?.timestamp) {
        startTime = new Date(data.records[0].timestamp);
      } else if (data.file_ids?.[0]?.time_created) {
        startTime = new Date(data.file_ids[0].time_created);
      }
    });

    return startTime;
  } catch {
    return null;
  }
}

/**
 * Scan the configured FIT folder and build an index of files + start times.
 * Caches for 60 seconds to avoid rescanning on every request.
 */
function scanFitLibrary(quiet = false) {
  const folder = getFitFolder();
  if (!folder) return [];

  const now = Date.now();
  // Use short 5-second cache so polling picks up new downloads quickly
  if (fitLibraryCache.folder === folder && (now - fitLibraryCache.scannedAt) < 5000) {
    return fitLibraryCache.files;
  }

  if (!quiet) console.log(`[FIT Library] Scanning ${folder}...`);
  const fitPaths = findFitFiles(folder);
  if (!quiet) console.log(`[FIT Library] Found ${fitPaths.length} .FIT files, indexing start times...`);

  const files = [];
  for (const fp of fitPaths) {
    const startTime = getFitStartTime(fp);
    if (startTime && !isNaN(startTime.getTime())) {
      files.push({ path: fp, startTime });
    }
  }

  files.sort((a, b) => b.startTime - a.startTime); // newest first
  const prevCount = fitLibraryCache.files?.length || 0;
  fitLibraryCache = { folder, files, scannedAt: now };
  if (!quiet || files.length !== prevCount) {
    console.log(`[FIT Library] Indexed ${files.length} files with valid timestamps`);
  }
  return files;
}

/**
 * Find the FIT file whose start time is closest to the given activity start time.
 * Returns the file entry or null if nothing within 5 minutes.
 */
function findMatchingFit(activityStartTime) {
  const files = scanFitLibrary();
  if (files.length === 0) return null;

  const targetMs = new Date(activityStartTime).getTime();
  if (isNaN(targetMs)) return null;

  let best = null;
  let bestDiff = Infinity;

  for (const f of files) {
    const diff = Math.abs(f.startTime.getTime() - targetMs);
    if (diff < bestDiff) {
      bestDiff = diff;
      best = f;
    }
  }

  // Accept matches within 5 minutes (Strava sometimes adjusts start time)
  const MAX_DIFF_MS = 5 * 60 * 1000;
  if (bestDiff <= MAX_DIFF_MS) {
    return best;
  }
  return null;
}

// API: Get FIT library status
app.get('/api/fit-library/status', (req, res) => {
  const folder = getFitFolder();
  if (!folder) {
    return res.json({ configured: false, folder: null, fileCount: 0 });
  }

  const files = scanFitLibrary();
  res.json({
    configured: true,
    folder,
    fileCount: files.length,
    newestFile: files[0]?.startTime || null,
    oldestFile: files[files.length - 1]?.startTime || null
  });
});

// API: Configure FIT library folder
app.post('/api/fit-library/configure', express.json(), (req, res) => {
  const { folder } = req.body;

  if (!folder || typeof folder !== 'string') {
    return res.status(400).json({ error: 'Folder path is required' });
  }

  const resolved = path.resolve(folder.trim());

  if (!fs.existsSync(resolved)) {
    return res.status(400).json({ error: `Folder not found: ${resolved}` });
  }

  if (!fs.statSync(resolved).isDirectory()) {
    return res.status(400).json({ error: `Not a directory: ${resolved}` });
  }

  setFitFolder(resolved);

  // Scan immediately to return count
  const files = scanFitLibrary();

  console.log(`\n✅ FIT Library folder set to: ${resolved} (${files.length} files indexed)`);

  res.json({
    configured: true,
    folder: resolved,
    fileCount: files.length,
    newestFile: files[0]?.startTime || null,
    oldestFile: files[files.length - 1]?.startTime || null
  });
});

// API: Auto-match a FIT file to a Strava activity by start time
app.get('/api/activity/:id/auto-fit', async (req, res) => {
  const folder = getFitFolder();
  if (!folder) {
    return res.json({ has_gear_data: false, source: 'fit_library', error: 'FIT library not configured' });
  }

  // Get activity start time from query param or fetch from Strava
  let startTime = req.query.start_date;

  if (!startTime) {
    // Fetch from Strava
    const token = await ensureValidToken(req);
    if (!token) return res.status(401).json({ error: 'Not authenticated' });

    try {
      const api = stravaApi(token);
      const resp = await api.get(`/activities/${req.params.id}`);
      startTime = resp.data.start_date;
    } catch (err) {
      return res.json({ has_gear_data: false, source: 'fit_library', error: 'Failed to fetch activity' });
    }
  }

  // Force rescan (quiet mode) so newly-downloaded files are picked up
  fitLibraryCache.scannedAt = 0;
  const match = findMatchingFit(startTime);
  if (!match) {
    return res.json({
      has_gear_data: false,
      source: 'fit_library',
      error: 'No matching FIT file found for this activity'
    });
  }

  console.log(`[FIT Library] Matched activity ${req.params.id} → ${path.basename(match.path)}`);

  // Parse the matched FIT file
  try {
    const fileBuffer = fs.readFileSync(match.path);
    const fitParser = new FitParser({
      force: true,
      speedUnit: 'km/h',
      lengthUnit: 'km',
      temperatureUnit: 'celsius',
      elapsedRecordField: true,
      mode: 'both'
    });

    fitParser.parse(fileBuffer, (error, data) => {
      if (error) {
        return res.json({ has_gear_data: false, source: 'fit_library', error: 'Failed to parse FIT file' });
      }

      const result = extractDi2Data(data);
      result.source = 'fit_library';
      result.matched_file = path.basename(match.path);
      res.json(result);
    });
  } catch (err) {
    console.error('[FIT Library] Parse error:', err.message);
    res.json({ has_gear_data: false, source: 'fit_library', error: 'Failed to read FIT file' });
  }
});

// API: Rescan FIT library (force cache invalidation)
app.post('/api/fit-library/rescan', (req, res) => {
  fitLibraryCache = { folder: null, files: [], scannedAt: 0 };
  const files = scanFitLibrary();
  res.json({ fileCount: files.length });
});

// ─── Setup Page HTML ────────────────────────────────────────────────────────

function getSetupPageHtml() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Setup — Di2va</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap">
  <style>
    :root {
      --bg: #0f1117; --bg-card: #1a1d27; --border: #2a2d3a;
      --text: #e4e4e7; --text-muted: #8b8fa3; --accent: #fc4c02;
      --accent-hover: #e04400; --blue: #3b82f6; --green: #22c55e;
      --radius: 8px; --font: 'Inter', -apple-system, sans-serif;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: var(--font); background: var(--bg); color: var(--text);
           display: flex; align-items: center; justify-content: center;
           min-height: 100vh; padding: 24px; -webkit-font-smoothing: antialiased; }
    .card { background: var(--bg-card); border: 1px solid var(--border);
            border-radius: 16px; padding: 40px; max-width: 520px; width: 100%; }
    .logo { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
    .logo svg { width: 32px; height: 32px; color: var(--accent); }
    .logo h1 { font-size: 1.3rem; font-weight: 700; letter-spacing: -0.02em; }
    .subtitle { color: var(--text-muted); margin-bottom: 28px; font-size: 0.95rem; line-height: 1.5; }
    .steps { background: rgba(59,130,246,0.08); border: 1px solid rgba(59,130,246,0.2);
             border-radius: var(--radius); padding: 16px 20px; margin-bottom: 28px; font-size: 0.85rem; }
    .steps h3 { color: var(--blue); font-size: 0.8rem; text-transform: uppercase;
                letter-spacing: 0.06em; margin-bottom: 8px; }
    .steps ol { padding-left: 18px; color: var(--text-muted); }
    .steps ol li { margin-bottom: 4px; }
    .steps a { color: var(--blue); text-decoration: underline; }
    label { display: block; font-size: 0.8rem; font-weight: 600;
            text-transform: uppercase; letter-spacing: 0.04em;
            color: var(--text-muted); margin-bottom: 6px; margin-top: 18px; }
    label:first-of-type { margin-top: 0; }
    input[type="text"], input[type="password"] {
      width: 100%; padding: 10px 14px; background: var(--bg);
      border: 1px solid var(--border); border-radius: var(--radius);
      color: var(--text); font-family: var(--font); font-size: 0.95rem;
      outline: none; transition: border-color 0.15s; }
    input:focus { border-color: var(--accent); }
    .hint { font-size: 0.75rem; color: var(--text-muted); margin-top: 4px; }
    button { display: block; width: 100%; margin-top: 28px; padding: 12px;
             background: var(--accent); color: #fff; border: none;
             border-radius: var(--radius); font-family: var(--font);
             font-size: 1rem; font-weight: 600; cursor: pointer;
             transition: background 0.15s; }
    button:hover { background: var(--accent-hover); }
    .footer { text-align: center; margin-top: 16px; font-size: 0.75rem; color: var(--text-muted); }
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="5" cy="18" r="3"/><circle cx="19" cy="18" r="3"/>
        <path d="M5 18l4-8 4 4 6-10"/>
      </svg>
      <h1>Di2va</h1>
    </div>
    <p class="subtitle">Welcome! To get started, connect your Strava API application. This only takes a minute.</p>

    <div class="steps">
      <h3>Before you begin</h3>
      <ol>
        <li>Go to <a href="https://www.strava.com/settings/api" target="_blank">strava.com/settings/api</a></li>
        <li>Create an application (Category: <strong>Visualizer</strong>)</li>
        <li>Set <strong>Authorization Callback Domain</strong> to <code>localhost</code></li>
        <li>Copy your <strong>Client ID</strong> and <strong>Client Secret</strong> below</li>
      </ol>
    </div>

    <form method="POST" action="/setup">
      <label for="client_id">Strava Client ID</label>
      <input type="text" id="client_id" name="client_id" placeholder="e.g. 12345" required autofocus>

      <label for="client_secret">Strava Client Secret</label>
      <input type="password" id="client_secret" name="client_secret" placeholder="e.g. abc123def456..." required>

      <label for="session_secret">Session Secret <span style="font-weight:400;text-transform:none">(optional)</span></label>
      <input type="text" id="session_secret" name="session_secret" placeholder="Auto-generated if left blank">
      <p class="hint">A random string used to sign session cookies. Leave blank to auto-generate.</p>

      <button type="submit">Save &amp; Connect to Strava →</button>
    </form>
    <p class="footer">Credentials are saved to <code>.env.local</code> which is gitignored and never committed.</p>
  </div>
</body>
</html>`;
}

// ─── Start Server ───────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`\n🚴 Di2va running at http://localhost:${PORT}`);

  if (!isStravaConfigured()) {
    console.log(`\n  ⚡ First-time setup required!`);
    console.log(`  → Open http://localhost:${PORT}/setup to configure your Strava API credentials\n`);
  } else {
    console.log(`  ✅ Strava API configured`);
  }

  const fitFolder = getFitFolder();
  if (fitFolder) {
    const files = scanFitLibrary();
    console.log(`  📂 FIT Library: ${fitFolder} (${files.length} files indexed)\n`);
  } else {
    console.log(`  📂 FIT Library: not configured — set via Settings in the app\n`);
  }
});
