// Load .env.local first (secrets), then .env (defaults) — neither is committed to git
require('dotenv').config({ path: require('path').join(__dirname, '.env.local') });
require('dotenv').config(); // won't overwrite values already set by .env.local
const express = require('express');
const session = require('express-session');
const axios = require('axios');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const os = require('os');
const FitParser = require('fit-file-parser').default;

const app = express();
const PORT = process.env.PORT || 3000;

// Ensure uploads directory exists
const uploadDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}

const upload = multer({ dest: uploadDir });

// Middleware
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: false, limit: '50mb' }));
app.use(express.static(path.join(__dirname, 'public'), {
  etag: false,
  lastModified: true,
  setHeaders: (res) => {
    res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  }
}));
app.use(session({
  secret: process.env.SESSION_SECRET || 'di2va-secret',
  resave: false,
  saveUninitialized: false,
  cookie: { maxAge: 24 * 60 * 60 * 1000 } // 24 hours
}));

// ─── Setup / First-Run Configuration ────────────────────────────────────────

function isStravaConfigured() {
  return process.env.STRAVA_CLIENT_ID &&
         process.env.STRAVA_CLIENT_ID.trim() !== '' &&
         process.env.STRAVA_CLIENT_SECRET &&
         process.env.STRAVA_CLIENT_SECRET.trim() !== '';
}

// Serve setup page
app.get('/setup', (req, res) => {
  if (isStravaConfigured()) return res.redirect('/');
  res.send(getSetupPageHtml());
});

// Save credentials from setup form
app.post('/setup', express.urlencoded({ extended: false }), (req, res) => {
  const { client_id, client_secret, session_secret } = req.body;

  if (!client_id || !client_secret) {
    return res.status(400).send('Client ID and Client Secret are required.');
  }

  // Write secrets to .env.local (gitignored — never committed)
  const envLocalPath = path.join(__dirname, '.env.local');
  const envContent = [
    '# Auto-generated by setup wizard — DO NOT commit this file',
    `STRAVA_CLIENT_ID=${client_id.trim()}`,
    `STRAVA_CLIENT_SECRET=${client_secret.trim()}`,
    `SESSION_SECRET=${(session_secret || '').trim() || require('crypto').randomBytes(32).toString('hex')}`,
  ].join('\n') + '\n';

  fs.writeFileSync(envLocalPath, envContent, { mode: 0o600 }); // owner-only read/write

  // Hot-reload into current process
  process.env.STRAVA_CLIENT_ID = client_id.trim();
  process.env.STRAVA_CLIENT_SECRET = client_secret.trim();
  if (session_secret) process.env.SESSION_SECRET = session_secret.trim();

  console.log('\n✅ Strava API credentials saved to .env.local (gitignored)');
  res.redirect('/');
});

// Redirect everything to /setup when not configured (except static assets)
app.use((req, res, next) => {
  if (isStravaConfigured()) return next();
  // Allow setup routes, auth routes, and static assets through
  if (req.path === '/setup' || req.path.startsWith('/auth/') || req.path.match(/\.(css|js|ico|png|jpg|svg|woff2?)$/)) {
    return next();
  }
  res.redirect('/setup');
});

// ─── Strava OAuth ───────────────────────────────────────────────────────────

const STRAVA_AUTH_URL = 'https://www.strava.com/oauth/authorize';
const STRAVA_TOKEN_URL = 'https://www.strava.com/oauth/token';
const STRAVA_API_BASE = 'https://www.strava.com/api/v3';

app.get('/auth/strava', (req, res) => {
  const params = new URLSearchParams({
    client_id: process.env.STRAVA_CLIENT_ID,
    redirect_uri: process.env.CALLBACK_URL || `http://localhost:${PORT}/auth/strava/callback`,
    response_type: 'code',
    scope: 'read,activity:read_all',
    approval_prompt: 'auto'
  });
  res.redirect(`${STRAVA_AUTH_URL}?${params}`);
});

app.get('/auth/strava/callback', async (req, res) => {
  const { code } = req.query;
  if (!code) {
    return res.redirect('/?error=no_code');
  }

  try {
    const response = await axios.post(STRAVA_TOKEN_URL, {
      client_id: process.env.STRAVA_CLIENT_ID,
      client_secret: process.env.STRAVA_CLIENT_SECRET,
      code,
      grant_type: 'authorization_code'
    });

    req.session.strava = {
      access_token: response.data.access_token,
      refresh_token: response.data.refresh_token,
      expires_at: response.data.expires_at,
      athlete: response.data.athlete
    };

    res.redirect('/');
  } catch (err) {
    console.error('OAuth error:', err.response?.data || err.message);
    res.redirect('/?error=auth_failed');
  }
});

app.get('/auth/logout', (req, res) => {
  req.session.destroy();
  res.redirect('/');
});

// ─── Auth middleware ─────────────────────────────────────────────────────────

async function ensureValidToken(req) {
  const strava = req.session.strava;
  if (!strava) return null;

  // Refresh token if expired (or within 5 minutes of expiry)
  if (strava.expires_at < (Date.now() / 1000) + 300) {
    try {
      const response = await axios.post(STRAVA_TOKEN_URL, {
        client_id: process.env.STRAVA_CLIENT_ID,
        client_secret: process.env.STRAVA_CLIENT_SECRET,
        refresh_token: strava.refresh_token,
        grant_type: 'refresh_token'
      });
      strava.access_token = response.data.access_token;
      strava.refresh_token = response.data.refresh_token;
      strava.expires_at = response.data.expires_at;
    } catch (err) {
      console.error('Token refresh error:', err.response?.data || err.message);
      return null;
    }
  }

  return strava.access_token;
}

function stravaApi(token) {
  return axios.create({
    baseURL: STRAVA_API_BASE,
    headers: { Authorization: `Bearer ${token}` }
  });
}

// ─── API Routes ─────────────────────────────────────────────────────────────

app.get('/api/me', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });
  res.json(req.session.strava.athlete);
});

app.get('/api/activities', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const page = req.query.page || 1;
    const perPage = req.query.per_page || 30;
    const api = stravaApi(token);
    const response = await api.get('/athlete/activities', {
      params: { page, per_page: perPage }
    });

    // Filter to rides only
    const rides = response.data.filter(a => a.type === 'Ride' || a.type === 'VirtualRide');
    res.json(rides);
  } catch (err) {
    console.error('Activities error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to fetch activities' });
  }
});

app.get('/api/activity/:id', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const api = stravaApi(token);
    const response = await api.get(`/activities/${req.params.id}`);
    res.json(response.data);
  } catch (err) {
    console.error('Activity error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to fetch activity' });
  }
});

app.get('/api/activity/:id/streams', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const api = stravaApi(token);
    // Request all available stream types
    const streamTypes = [
      'time', 'latlng', 'altitude', 'distance',
      'heartrate', 'cadence', 'watts', 'temp',
      'moving', 'grade_smooth', 'velocity_smooth'
    ].join(',');

    const response = await api.get(`/activities/${req.params.id}/streams`, {
      params: { keys: streamTypes, key_type: 'distance' }
    });

    // Convert array of streams to an object keyed by type
    const streams = {};
    response.data.forEach(stream => {
      streams[stream.type] = stream.data;
    });

    res.json(streams);
  } catch (err) {
    console.error('Streams error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to fetch streams' });
  }
});

// ─── Fetch & Parse Original FIT File from Strava ────────────────────────────

app.get('/api/activity/:id/fit-gear-data', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    // Strava exposes the original uploaded file at this endpoint.
    // NOTE: This is not an official public API — it may return 403 or redirect
    // to a web login page. When it fails we fall back to gear estimation.
    console.log(`Fetching original FIT for activity ${req.params.id}...`);
    const response = await axios.get(
      `${STRAVA_API_BASE}/activities/${req.params.id}/export_original`,
      {
        headers: { Authorization: `Bearer ${token}` },
        responseType: 'arraybuffer',
        timeout: 30000,
        maxRedirects: 5
      }
    );

    const contentType = response.headers['content-type'] || '';
    const buffer = Buffer.from(response.data);
    console.log(`  Got ${buffer.length} bytes, content-type: ${contentType}`);

    // Check if we actually got a FIT file (starts with header size byte + ".FIT")
    const isFit = buffer.length > 12 &&
                  buffer.toString('ascii', 8, 12) === '.FIT';

    if (!isFit && !contentType.includes('octet-stream') && !contentType.includes('fit')) {
      return res.json({
        has_gear_data: false,
        source: 'strava_export',
        error: 'Original file is not a FIT file (may be GPX or TCX)'
      });
    }

    // Parse the FIT file
    const fitParser = new FitParser({
      force: true,
      speedUnit: 'km/h',
      lengthUnit: 'km',
      temperatureUnit: 'celsius',
      elapsedRecordField: true,
      mode: 'both'
    });

    fitParser.parse(buffer, (error, data) => {
      if (error) {
        console.error('FIT parse error (from Strava):', error);
        return res.json({
          has_gear_data: false,
          source: 'strava_export',
          error: 'Failed to parse FIT file'
        });
      }

      const result = extractDi2Data(data);
      result.source = 'strava_export';
      res.json(result);
    });

  } catch (err) {
    const status = err.response?.status;
    // 404 = no original file, 403 = not authorized for this activity
    if (status === 404 || status === 403) {
      return res.json({
        has_gear_data: false,
        source: 'strava_export',
        error: status === 404
          ? 'No original file available for this activity'
          : 'Not authorized to access original file'
      });
    }
    console.error('FIT fetch error:', status, err.message);
    console.log('  → This is expected — export_original is not an official Strava API endpoint.');
    console.log('  → For actual Di2 data, upload the .FIT file from your bike computer.');
    res.json({
      has_gear_data: false,
      source: 'strava_export',
      error: 'Failed to fetch original file from Strava'
    });
  }
});

// ─── FIT File Upload & Parsing ──────────────────────────────────────────────

app.post('/api/parse-fit', upload.single('fitfile'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file uploaded' });
  }

  const filePath = req.file.path;

  try {
    const fileBuffer = fs.readFileSync(filePath);
    const fitParser = new FitParser({
      force: true,
      speedUnit: 'km/h',
      lengthUnit: 'km',
      temperatureUnit: 'celsius',
      elapsedRecordField: true,
      mode: 'both'
    });

    fitParser.parse(fileBuffer, (error, data) => {
      // Clean up uploaded file
      fs.unlinkSync(filePath);

      if (error) {
        console.error('FIT parse error:', error);
        return res.status(400).json({ error: 'Failed to parse FIT file' });
      }

      // Extract gear shift data from events and records
      const result = extractDi2Data(data);
      res.json(result);
    });
  } catch (err) {
    // Clean up on error
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
    console.error('FIT processing error:', err);
    res.status(500).json({ error: 'Failed to process FIT file' });
  }
});

/**
 * Decode gear data packed in a FIT event's uint32 `data` field.
 * Layout: byte0 = rear_gear_num, byte1 = rear_gear_teeth,
 *         byte2 = front_gear_num, byte3 = front_gear_teeth
 */
function decodeGearData(data) {
  if (typeof data !== 'number' || data === 0) return null;
  return {
    rear_gear_num:    data & 0xFF,
    rear_gear_teeth:  (data >> 8) & 0xFF,
    front_gear_num:   (data >> 16) & 0xFF,
    front_gear_teeth: (data >> 24) & 0xFF
  };
}

/**
 * Extract Di2 gear shift data from parsed FIT file.
 * Handles rear_gear_change / front_gear_change events (Garmin)
 * and the older gear_change event type.
 */
function extractDi2Data(fitData) {
  const gearChanges = [];
  const records = [];

  // Extract gear change events — match all known event names
  if (fitData.events) {
    fitData.events.forEach(event => {
      const isGearEvent =
        event.event === 'rear_gear_change' ||
        event.event === 'front_gear_change' ||
        event.event === 'gear_change' ||
        event.event_type === 'gear_change';

      if (!isGearEvent) return;

      // Try named fields first (some parsers expand them),
      // then decode from the packed uint32 data field
      let rearNum   = event.rear_gear_num;
      let rearTeeth = event.rear_gear_teeth;
      let frontNum  = event.front_gear_num;
      let frontTeeth = event.front_gear_teeth;

      if (rearTeeth === undefined && event.data !== undefined) {
        const decoded = decodeGearData(event.data);
        if (decoded) {
          rearNum   = decoded.rear_gear_num;
          rearTeeth = decoded.rear_gear_teeth;
          frontNum  = decoded.front_gear_num;
          frontTeeth = decoded.front_gear_teeth;
        }
      }

      gearChanges.push({
        timestamp: event.timestamp,
        event_type: event.event,          // 'rear_gear_change' or 'front_gear_change'
        rear_gear_num:    rearNum   || null,
        rear_gear_teeth:  rearTeeth || null,
        front_gear_num:   frontNum  || null,
        front_gear_teeth: frontTeeth || null,
        gear_ratio: (frontTeeth && rearTeeth) ? +(frontTeeth / rearTeeth).toFixed(2) : null
      });
    });
  }

  // Sort gear changes by timestamp (they should already be, but be safe)
  gearChanges.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));

  // Extract per-record data (records have timestamps, position, gear info etc.)
  if (fitData.records) {
    fitData.records.forEach(record => {
      const rec = {
        timestamp: record.timestamp,
        elapsed_time: record.elapsed_time,
        distance: record.distance,
        position_lat: record.position_lat,
        position_long: record.position_long,
        altitude: record.altitude || record.enhanced_altitude,
        speed: record.speed || record.enhanced_speed,
        cadence: record.cadence,
        power: record.power,
        heart_rate: record.heart_rate,
        temperature: record.temperature
      };

      // Di2 specific fields that may appear directly in records
      if (record.rear_gear_num !== undefined) rec.rear_gear_num = record.rear_gear_num;
      if (record.rear_gear_teeth !== undefined) rec.rear_gear_teeth = record.rear_gear_teeth;
      if (record.front_gear_num !== undefined) rec.front_gear_num = record.front_gear_num;
      if (record.front_gear_teeth !== undefined) rec.front_gear_teeth = record.front_gear_teeth;
      if (record.left_right_balance !== undefined) rec.left_right_balance = record.left_right_balance;

      records.push(rec);
    });
  }

  // Merge gear change events into records by timestamp
  if (gearChanges.length > 0 && records.length > 0) {
    let gearIdx = 0;
    let currentGear = {
      front_gear_num:   gearChanges[0].front_gear_num,
      front_gear_teeth: gearChanges[0].front_gear_teeth,
      rear_gear_num:    gearChanges[0].rear_gear_num,
      rear_gear_teeth:  gearChanges[0].rear_gear_teeth
    };

    records.forEach(record => {
      // Advance gear index to match timestamp
      while (gearIdx < gearChanges.length &&
             new Date(gearChanges[gearIdx].timestamp) <= new Date(record.timestamp)) {
        const gc = gearChanges[gearIdx];
        // Each event carries full state (front + rear), so update all fields
        if (gc.front_gear_num)   currentGear.front_gear_num   = gc.front_gear_num;
        if (gc.front_gear_teeth) currentGear.front_gear_teeth = gc.front_gear_teeth;
        if (gc.rear_gear_num)    currentGear.rear_gear_num    = gc.rear_gear_num;
        if (gc.rear_gear_teeth)  currentGear.rear_gear_teeth  = gc.rear_gear_teeth;
        gearIdx++;
      }

      // Apply current gear to record if not already set
      if (!record.rear_gear_num)    record.rear_gear_num    = currentGear.rear_gear_num;
      if (!record.rear_gear_teeth)  record.rear_gear_teeth  = currentGear.rear_gear_teeth;
      if (!record.front_gear_num)   record.front_gear_num   = currentGear.front_gear_num;
      if (!record.front_gear_teeth) record.front_gear_teeth = currentGear.front_gear_teeth;

      // Calculate gear ratio
      if (record.front_gear_teeth && record.rear_gear_teeth) {
        record.gear_ratio = +(record.front_gear_teeth / record.rear_gear_teeth).toFixed(2);
      }
    });
  }

  // Extract device info — match Shimano by string name or known manufacturer IDs
  // (manufacturer 41 = Shimano in some FIT profiles, or appears as numeric when
  //  the parser doesn't have the enum mapping)
  const SHIMANO_MFR_IDS = [41, 'shimano'];
  const deviceInfo = fitData.device_infos || [];
  const di2Devices = deviceInfo.filter(d =>
    SHIMANO_MFR_IDS.includes(d.manufacturer) ||
    (d.product_name && d.product_name.toLowerCase().includes('di2')) ||
    (d.product_name && d.product_name.toLowerCase().includes('shimano'))
  );

  const hasGearData = gearChanges.length > 0 ||
                      records.some(r => r.rear_gear_num !== undefined);

  console.log(`  Di2 extraction: ${gearChanges.length} gear changes, ` +
              `${records.length} records, has_gear_data=${hasGearData}`);

  return {
    gear_changes: gearChanges,
    records: records,
    di2_devices: di2Devices,
    session: fitData.sessions?.[0] || null,
    has_gear_data: hasGearData
  };
}

// ─── Gear Estimation from Cadence/Speed ─────────────────────────────────────

app.post('/api/estimate-gears', express.json(), (req, res) => {
  const { cadence, velocity_smooth, distance, latlng, altitude } = req.body;

  if (!cadence || !velocity_smooth) {
    return res.status(400).json({ error: 'Cadence and speed data required' });
  }

  // Common road bike gear configurations
  const CHAINRINGS = [34, 50]; // Compact: 34/50, Standard: 39/53
  const CASSETTE = [11, 12, 13, 14, 15, 17, 19, 21, 23, 25, 28]; // 11-28 cassette
  const WHEEL_CIRCUMFERENCE = 2.105; // meters (700x25c)

  const gearData = [];

  for (let i = 0; i < cadence.length; i++) {
    const rpm = cadence[i];
    const speed = velocity_smooth[i]; // m/s

    if (rpm <= 0 || speed <= 0.5) {
      gearData.push({
        index: i,
        front: null,
        rear: null,
        gear_ratio: null,
        estimated: true
      });
      continue;
    }

    // Calculate actual gear inches from speed and cadence
    // speed (m/s) = cadence (rpm) / 60 * gear_ratio * wheel_circumference
    const actualRatio = (speed / (rpm / 60)) / WHEEL_CIRCUMFERENCE;

    // Find closest matching gear combination
    let bestMatch = null;
    let bestDiff = Infinity;

    for (const front of CHAINRINGS) {
      for (const rear of CASSETTE) {
        const ratio = front / rear;
        const diff = Math.abs(ratio - actualRatio);
        if (diff < bestDiff) {
          bestDiff = diff;
          bestMatch = { front, rear, ratio };
        }
      }
    }

    gearData.push({
      index: i,
      front: bestMatch?.front || null,
      rear: bestMatch?.rear || null,
      gear_ratio: bestMatch?.ratio?.toFixed(2) || null,
      confidence: bestDiff < 0.15 ? 'high' : bestDiff < 0.3 ? 'medium' : 'low',
      estimated: true
    });
  }

  res.json({ gears: gearData });
});

// ─── AI Shifting Analysis ───────────────────────────────────────────────────

/**
 * Cycling best-practice shifting rules:
 * - Target cadence: 80–100 RPM (optimal ~90 RPM) — lower is grinding, higher is spinning out
 * - Gradient response: shift to easier gear before/during climbs, harder on descents
 * - Cross-chaining: avoid big chainring + big cog, or small chainring + small cog
 * - Shift smoothness: avoid rapid gear hunting (>3 shifts in 10 seconds)
 * - Anticipatory shifting: should shift BEFORE gradient steepens, not after
 *
 * Sources:
 *   - Shimano shifting guides: shift under light load, anticipate terrain
 *   - British Cycling / TrainingPeaks: 80-100 RPM target for most riding
 *   - Cross-chain guidance: increases wear, reduces efficiency
 */

const CHAINRINGS_ANALYSIS = [34, 50];
const CASSETTE_ANALYSIS = [11, 12, 13, 14, 15, 17, 19, 21, 23, 25, 28];
const WHEEL_CIRC = 2.105;

function buildGearTable() {
  const gears = [];
  for (const front of CHAINRINGS_ANALYSIS) {
    for (const rear of CASSETTE_ANALYSIS) {
      gears.push({ front, rear, ratio: front / rear });
    }
  }
  return gears.sort((a, b) => a.ratio - b.ratio);
}

function isCrossChained(front, rear) {
  const bigChainring = Math.max(...CHAINRINGS_ANALYSIS);
  const smallChainring = Math.min(...CHAINRINGS_ANALYSIS);
  const bigCog = Math.max(...CASSETTE_ANALYSIS);
  const smallCog = Math.min(...CASSETTE_ANALYSIS);
  const cassetteMid = CASSETTE_ANALYSIS.length / 2;
  const cogIndex = CASSETTE_ANALYSIS.indexOf(rear);

  // Big-big: big chainring + 3 biggest cogs
  if (front === bigChainring && cogIndex >= CASSETTE_ANALYSIS.length - 3) return true;
  // Small-small: small chainring + 3 smallest cogs
  if (front === smallChainring && cogIndex <= 2) return true;
  return false;
}

/**
 * For a given speed (m/s) and target cadence (RPM), find the optimal gear.
 */
function optimalGearForConditions(speed, gradient, gearTable) {
  if (speed < 0.5) return null;

  // Adjust target cadence based on gradient
  // Climbing: lower cadence is acceptable (75-90), flat: 85-95, descending: 90-100
  let targetCadence;
  if (gradient > 8) targetCadence = 75;
  else if (gradient > 5) targetCadence = 80;
  else if (gradient > 2) targetCadence = 85;
  else if (gradient > -2) targetCadence = 90;
  else if (gradient > -5) targetCadence = 92;
  else targetCadence = 95;

  // speed = (cadence / 60) * ratio * wheelCircumference
  // ratio = speed / ((cadence / 60) * wheelCircumference)
  const idealRatio = speed / ((targetCadence / 60) * WHEEL_CIRC);

  // Find closest gear, preferring non-cross-chained
  let bestGear = null;
  let bestScore = Infinity;

  for (const g of gearTable) {
    const ratioDiff = Math.abs(g.ratio - idealRatio);
    const crossPenalty = isCrossChained(g.front, g.rear) ? 0.3 : 0;
    const score = ratioDiff + crossPenalty;
    if (score < bestScore) {
      bestScore = score;
      bestGear = g;
    }
  }
  return bestGear;
}

function analyseShifting(streams, gearData) {
  const gearTable = buildGearTable();
  const len = Math.min(
    streams.distance?.length || 0,
    streams.cadence?.length || 0,
    streams.velocity_smooth?.length || 0,
    gearData.length
  );

  if (len === 0) return null;

  let cadenceScore = 0, cadenceCount = 0;
  let crossChainCount = 0, totalGearPoints = 0;
  let gearHuntingPenalty = 0;
  let gradientMatchScore = 0, gradientMatchCount = 0;
  const optimalGears = [];

  // Track recent shifts for gear hunting detection
  const recentShifts = [];

  for (let i = 0; i < len; i++) {
    const g = gearData[i];
    const cadence = streams.cadence?.[i];
    const speed = streams.velocity_smooth?.[i] || 0;
    const gradient = streams.grade_smooth?.[i] || 0;
    const time = streams.time?.[i] || i;

    // Optimal gear for this point
    const optimal = optimalGearForConditions(speed, gradient, gearTable);
    optimalGears.push(optimal ? { front: optimal.front, rear: optimal.rear } : null);

    if (!g?.front || !g?.rear || speed < 0.5) continue;

    totalGearPoints++;

    // 1. Cadence scoring (30%)
    if (cadence && cadence > 0) {
      cadenceCount++;
      if (cadence >= 80 && cadence <= 100) {
        cadenceScore += 1.0; // Perfect range
      } else if (cadence >= 70 && cadence <= 110) {
        cadenceScore += 0.6; // Acceptable
      } else if (cadence >= 60 && cadence <= 120) {
        cadenceScore += 0.3; // Poor
      }
      // else 0 — very poor
    }

    // 2. Cross-chain check (15%)
    if (isCrossChained(g.front, g.rear)) {
      crossChainCount++;
    }

    // 3. Gradient matching (25%)
    if (optimal) {
      const actualRatio = g.front / g.rear;
      const optimalRatio = optimal.ratio;
      const ratioDiff = Math.abs(actualRatio - optimalRatio);
      if (ratioDiff < 0.2) gradientMatchScore += 1.0;
      else if (ratioDiff < 0.5) gradientMatchScore += 0.6;
      else if (ratioDiff < 1.0) gradientMatchScore += 0.3;
      gradientMatchCount++;
    }

    // 4. Gear hunting detection (15%)
    if (i > 0 && gearData[i - 1]?.front && gearData[i - 1]?.rear) {
      const prev = gearData[i - 1];
      if (g.front !== prev.front || g.rear !== prev.rear) {
        recentShifts.push(time);
        // Count shifts in last ~10 data points
        const windowStart = time - 15;
        const windowShifts = recentShifts.filter(t => t >= windowStart).length;
        if (windowShifts > 3) gearHuntingPenalty++;
      }
    }
  }

  if (totalGearPoints === 0) return null;

  // Compute component scores (0-1)
  const cadenceComponent = cadenceCount > 0 ? cadenceScore / cadenceCount : 0.5;
  const crossChainComponent = 1 - (crossChainCount / totalGearPoints);
  const gradientComponent = gradientMatchCount > 0 ? gradientMatchScore / gradientMatchCount : 0.5;
  const huntingComponent = Math.max(0, 1 - (gearHuntingPenalty / (totalGearPoints * 0.05)));

  // Weighted overall score
  const overall = (
    cadenceComponent * 0.30 +
    crossChainComponent * 0.15 +
    gradientComponent * 0.25 +
    huntingComponent * 0.15 +
    0.15 * ((cadenceComponent + gradientComponent) / 2) // Anticipatory bonus
  );

  // Convert to 1-5 scale
  const rating = Math.max(1, Math.min(5, Math.round(overall * 5)));

  return {
    rating,
    overall: (overall * 100).toFixed(0),
    components: {
      cadence: { score: (cadenceComponent * 100).toFixed(0), label: 'Cadence Efficiency' },
      crossChain: { score: (crossChainComponent * 100).toFixed(0), label: 'Cross-Chain Avoidance' },
      gradient: { score: (gradientComponent * 100).toFixed(0), label: 'Gradient Matching' },
      hunting: { score: (huntingComponent * 100).toFixed(0), label: 'Shift Smoothness' }
    },
    stats: {
      totalPoints: totalGearPoints,
      crossChainPercent: ((crossChainCount / totalGearPoints) * 100).toFixed(1),
      avgCadenceInRange: cadenceCount > 0 ? ((cadenceScore / cadenceCount) * 100).toFixed(0) : 'N/A'
    },
    optimalGears
  };
}

app.get('/api/ai-analysis', async (req, res) => {
  const token = await ensureValidToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated' });

  try {
    const apiClient = stravaApi(token);

    // Fetch last 10 activities
    const activitiesRes = await apiClient.get('/athlete/activities', {
      params: { page: 1, per_page: 10 }
    });
    const rides = activitiesRes.data.filter(a => a.type === 'Ride' || a.type === 'VirtualRide');

    if (rides.length === 0) {
      return res.json({ error: 'No rides found' });
    }

    console.log(`🤖 AI Analysis: processing ${rides.length} rides...`);

    const activityResults = [];
    let aggregateScores = { cadence: 0, crossChain: 0, gradient: 0, hunting: 0 };
    let analysedCount = 0;

    for (const ride of rides.slice(0, 10)) {
      try {
        // Fetch streams
        const streamTypes = 'time,latlng,altitude,distance,cadence,watts,grade_smooth,velocity_smooth';
        const streamsRes = await apiClient.get(`/activities/${ride.id}/streams`, {
          params: { keys: streamTypes, key_type: 'distance' }
        });

        const streams = {};
        streamsRes.data.forEach(s => { streams[s.type] = s.data; });

        if (!streams.cadence || !streams.velocity_smooth) continue;

        // Estimate gears
        const gearData = [];
        for (let i = 0; i < streams.cadence.length; i++) {
          const rpm = streams.cadence[i];
          const speed = streams.velocity_smooth[i];
          if (rpm <= 0 || speed <= 0.5) {
            gearData.push({ front: null, rear: null });
            continue;
          }
          const actualRatio = (speed / (rpm / 60)) / WHEEL_CIRC;
          let bestMatch = null, bestDiff = Infinity;
          for (const front of CHAINRINGS_ANALYSIS) {
            for (const rear of CASSETTE_ANALYSIS) {
              const diff = Math.abs((front / rear) - actualRatio);
              if (diff < bestDiff) { bestDiff = diff; bestMatch = { front, rear }; }
            }
          }
          gearData.push(bestMatch || { front: null, rear: null });
        }

        const result = analyseShifting(streams, gearData);
        if (result) {
          activityResults.push({
            id: ride.id,
            name: ride.name,
            date: ride.start_date_local,
            rating: result.rating,
            overall: result.overall
          });
          aggregateScores.cadence += parseFloat(result.components.cadence.score);
          aggregateScores.crossChain += parseFloat(result.components.crossChain.score);
          aggregateScores.gradient += parseFloat(result.components.gradient.score);
          aggregateScores.hunting += parseFloat(result.components.hunting.score);
          analysedCount++;
        }
      } catch (e) {
        console.warn(`  Skipping ride ${ride.id}: ${e.message}`);
      }
    }

    if (analysedCount === 0) {
      return res.json({ error: 'No rides with sufficient data for analysis' });
    }

    // Average scores
    const avg = {
      cadence: (aggregateScores.cadence / analysedCount).toFixed(0),
      crossChain: (aggregateScores.crossChain / analysedCount).toFixed(0),
      gradient: (aggregateScores.gradient / analysedCount).toFixed(0),
      hunting: (aggregateScores.hunting / analysedCount).toFixed(0)
    };

    const overallPct = (
      avg.cadence * 0.30 + avg.crossChain * 0.15 +
      avg.gradient * 0.25 + avg.hunting * 0.15 +
      0.15 * ((parseFloat(avg.cadence) + parseFloat(avg.gradient)) / 2)
    );
    const overallRating = Math.max(1, Math.min(5, Math.round(overallPct / 20)));

    // Generate text summary
    const stars = '★'.repeat(overallRating) + '☆'.repeat(5 - overallRating);
    let summary = `Shifting Analysis — ${stars} (${overallRating}/5)\n`;
    summary += `Based on your last ${analysedCount} ride${analysedCount > 1 ? 's' : ''}:\n\n`;

    // Cadence feedback
    if (parseInt(avg.cadence) >= 80) {
      summary += `✅ Cadence Efficiency (${avg.cadence}%): Excellent — you're maintaining a healthy cadence range (80–100 RPM) through most of your rides. This is kind to your knees and efficient for power delivery.\n\n`;
    } else if (parseInt(avg.cadence) >= 60) {
      summary += `⚠️ Cadence Efficiency (${avg.cadence}%): Room for improvement — you're often riding outside the optimal 80–100 RPM range. Try shifting to an easier gear on climbs rather than grinding at low cadence, and shift harder on descents to avoid spinning out.\n\n`;
    } else {
      summary += `❌ Cadence Efficiency (${avg.cadence}%): Needs attention — you're frequently grinding in too hard a gear or spinning too fast. The target is 80–100 RPM for most conditions. Shift earlier and more frequently to stay in the sweet spot.\n\n`;
    }

    // Cross-chain feedback
    if (parseInt(avg.crossChain) >= 90) {
      summary += `✅ Cross-Chain Avoidance (${avg.crossChain}%): Great — you're rarely cross-chaining. This reduces drivetrain wear and improves efficiency.\n\n`;
    } else if (parseInt(avg.crossChain) >= 70) {
      summary += `⚠️ Cross-Chain Avoidance (${avg.crossChain}%): Moderate — you're sometimes in big/big or small/small combinations. Try to avoid the big chainring with the 3 largest cogs, or the small chainring with the 3 smallest cogs.\n\n`;
    } else {
      summary += `❌ Cross-Chain Avoidance (${avg.crossChain}%): High cross-chain usage — shift to the other chainring more often. Cross-chaining increases wear and reduces power transfer.\n\n`;
    }

    // Gradient matching feedback
    if (parseInt(avg.gradient) >= 75) {
      summary += `✅ Gradient Matching (${avg.gradient}%): Good — your gear selection matches the terrain well. You're choosing appropriate gears for climbs, flats, and descents.\n\n`;
    } else if (parseInt(avg.gradient) >= 50) {
      summary += `⚠️ Gradient Matching (${avg.gradient}%): Fair — you could better match your gearing to the gradient. Consider shifting to easier gears earlier when approaching a climb, and harder gears as the road levels out.\n\n`;
    } else {
      summary += `❌ Gradient Matching (${avg.gradient}%): Poor terrain matching — you're often in the wrong gear for the gradient. Anticipate hills by shifting before the gradient increases.\n\n`;
    }

    // Shift smoothness feedback
    if (parseInt(avg.hunting) >= 85) {
      summary += `✅ Shift Smoothness (${avg.hunting}%): Smooth shifting — you're not gear hunting. Consistent gear choices show good judgment.\n\n`;
    } else if (parseInt(avg.hunting) >= 60) {
      summary += `⚠️ Shift Smoothness (${avg.hunting}%): Some gear hunting detected — you're occasionally shifting back and forth rapidly. Try to commit to a gear and give it a few seconds before deciding to shift again.\n\n`;
    } else {
      summary += `❌ Shift Smoothness (${avg.hunting}%): Frequent gear hunting — lots of rapid back-and-forth shifts. This suggests indecision or incorrect initial gear choice. Anticipate the terrain and commit to your shift.\n\n`;
    }

    summary += `💡 Tip: The optimal cadence for road cycling is 80–100 RPM for most riders. Shift to maintain this range as the terrain changes. Anticipate gradient changes and shift before the hill, not on it.`;

    console.log(`🤖 AI Analysis complete: ${overallRating}/5 across ${analysedCount} rides`);

    res.json({
      rating: overallRating,
      overallPercent: overallPct.toFixed(0),
      summary,
      components: {
        cadence: avg.cadence,
        crossChain: avg.crossChain,
        gradient: avg.gradient,
        hunting: avg.hunting
      },
      activities: activityResults,
      analysedCount
    });

  } catch (err) {
    console.error('AI Analysis error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to run analysis' });
  }
});

/**
 * Get optimal gear overlay data for the currently viewed activity.
 * Uses the same analysis engine but returns per-point optimal gears.
 */
app.post('/api/optimal-gears', express.json(), (req, res) => {
  const { cadence, velocity_smooth, grade_smooth, distance } = req.body;

  if (!cadence || !velocity_smooth) {
    return res.status(400).json({ error: 'Cadence and speed data required' });
  }

  const gearTable = buildGearTable();
  const optimalGears = [];

  for (let i = 0; i < cadence.length; i++) {
    const speed = velocity_smooth[i] || 0;
    const gradient = grade_smooth?.[i] || 0;
    const optimal = optimalGearForConditions(speed, gradient, gearTable);
    optimalGears.push(optimal ? { front: optimal.front, rear: optimal.rear } : null);
  }

  res.json({ optimalGears });
});

// ─── FIT Library — Auto-match FIT files to Strava activities ────────────────

/**
 * Scan a directory (recursively) for .FIT files and extract their start time
 * by parsing just the session header. Returns an array of { path, startTime }.
 *
 * Results are cached in memory and refreshed when the folder changes.
 */
let fitLibraryCache = { folder: null, files: [], scannedAt: 0 };

function getFitFolder() {
  const configured = (process.env.FIT_FOLDER || '').trim();
  if (configured) return configured;
  // Default to the system's actual download folder
  return getDefaultDownloadFolder();
}

/**
 * Detect the system's default download folder.
 * On macOS, reads the user's com.apple.finder plist for the configured
 * download location. Falls back to ~/Downloads.
 */
function getDefaultDownloadFolder() {
  // Try macOS-specific detection
  if (process.platform === 'darwin') {
    try {
      const { execSync } = require('child_process');
      // NSNavLastRootDirectory in Finder prefs sometimes has the download path
      // but the most reliable approach is simply ~/Downloads which macOS always uses
      // unless the user has manually moved it (extremely rare).
    } catch (e) { /* ignore */ }
  }
  const downloads = path.join(os.homedir(), 'Downloads');
  return fs.existsSync(downloads) ? downloads : '';
}

function setFitFolder(folder) {
  process.env.FIT_FOLDER = folder;
  fitLibraryCache = { folder: null, files: [], scannedAt: 0 }; // invalidate

  // Persist to .env.local
  const envLocalPath = path.join(__dirname, '.env.local');
  let content = '';
  if (fs.existsSync(envLocalPath)) {
    content = fs.readFileSync(envLocalPath, 'utf8');
    // Remove existing FIT_FOLDER line
    content = content.replace(/^FIT_FOLDER=.*\n?/m, '');
  }
  content = content.trimEnd() + `\nFIT_FOLDER=${folder}\n`;
  fs.writeFileSync(envLocalPath, content, { mode: 0o600 });
}

/**
 * Recursively find all .fit/.FIT files in a directory.
 */
function findFitFiles(dir, maxDepth = 3, depth = 0) {
  if (depth > maxDepth) return [];
  const results = [];
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        results.push(...findFitFiles(fullPath, maxDepth, depth + 1));
      } else if (entry.isFile() && /\.fit$/i.test(entry.name)) {
        results.push(fullPath);
      }
    }
  } catch (err) {
    // Permission denied or missing dir — skip silently
  }
  return results;
}

/**
 * Quick-parse a FIT file to extract just the session start time.
 * Returns a Date or null.
 */
function getFitStartTime(filePath) {
  try {
    const buf = fs.readFileSync(filePath);
    // Quick sanity check for FIT header
    if (buf.length < 14 || buf.toString('ascii', 8, 12) !== '.FIT') return null;

    const parser = new FitParser({ force: true, mode: 'list' });
    let startTime = null;

    // Synchronous: parse returns via callback immediately for file buffer
    parser.parse(buf, (err, data) => {
      if (err) return;
      // Try session start_time first, then first record timestamp, then file_id time_created
      if (data.sessions?.[0]?.start_time) {
        startTime = new Date(data.sessions[0].start_time);
      } else if (data.records?.[0]?.timestamp) {
        startTime = new Date(data.records[0].timestamp);
      } else if (data.file_ids?.[0]?.time_created) {
        startTime = new Date(data.file_ids[0].time_created);
      }
    });

    return startTime;
  } catch {
    return null;
  }
}

/**
 * Scan the configured FIT folder and build an index of files + start times.
 * Caches for 60 seconds to avoid rescanning on every request.
 */
function scanFitLibrary(quiet = false) {
  const folder = getFitFolder();
  if (!folder) return [];

  const now = Date.now();
  // Use short 5-second cache so polling picks up new downloads quickly
  if (fitLibraryCache.folder === folder && (now - fitLibraryCache.scannedAt) < 5000) {
    return fitLibraryCache.files;
  }

  if (!quiet) console.log(`[FIT Library] Scanning ${folder}...`);
  const fitPaths = findFitFiles(folder);
  if (!quiet) console.log(`[FIT Library] Found ${fitPaths.length} .FIT files, indexing start times...`);

  const files = [];
  for (const fp of fitPaths) {
    const startTime = getFitStartTime(fp);
    if (startTime && !isNaN(startTime.getTime())) {
      files.push({ path: fp, startTime });
    }
  }

  files.sort((a, b) => b.startTime - a.startTime); // newest first
  const prevCount = fitLibraryCache.files?.length || 0;
  fitLibraryCache = { folder, files, scannedAt: now };
  if (!quiet || files.length !== prevCount) {
    console.log(`[FIT Library] Indexed ${files.length} files with valid timestamps`);
  }
  return files;
}

/**
 * Find the FIT file whose start time is closest to the given activity start time.
 * Returns the file entry or null if nothing within 5 minutes.
 */
function findMatchingFit(activityStartTime) {
  const files = scanFitLibrary();
  if (files.length === 0) return null;

  const targetMs = new Date(activityStartTime).getTime();
  if (isNaN(targetMs)) return null;

  let best = null;
  let bestDiff = Infinity;

  for (const f of files) {
    const diff = Math.abs(f.startTime.getTime() - targetMs);
    if (diff < bestDiff) {
      bestDiff = diff;
      best = f;
    }
  }

  // Accept matches within 5 minutes (Strava sometimes adjusts start time)
  const MAX_DIFF_MS = 5 * 60 * 1000;
  if (bestDiff <= MAX_DIFF_MS) {
    return best;
  }
  return null;
}

// API: Get FIT library status
app.get('/api/fit-library/status', (req, res) => {
  const folder = getFitFolder();
  if (!folder) {
    return res.json({ configured: false, folder: null, fileCount: 0 });
  }

  const files = scanFitLibrary();
  res.json({
    configured: true,
    folder,
    fileCount: files.length,
    newestFile: files[0]?.startTime || null,
    oldestFile: files[files.length - 1]?.startTime || null
  });
});

// API: Configure FIT library folder
app.post('/api/fit-library/configure', express.json(), (req, res) => {
  const { folder } = req.body;

  if (!folder || typeof folder !== 'string') {
    return res.status(400).json({ error: 'Folder path is required' });
  }

  const resolved = path.resolve(folder.trim());

  if (!fs.existsSync(resolved)) {
    return res.status(400).json({ error: `Folder not found: ${resolved}` });
  }

  if (!fs.statSync(resolved).isDirectory()) {
    return res.status(400).json({ error: `Not a directory: ${resolved}` });
  }

  setFitFolder(resolved);

  // Scan immediately to return count
  const files = scanFitLibrary();

  console.log(`\n✅ FIT Library folder set to: ${resolved} (${files.length} files indexed)`);

  res.json({
    configured: true,
    folder: resolved,
    fileCount: files.length,
    newestFile: files[0]?.startTime || null,
    oldestFile: files[files.length - 1]?.startTime || null
  });
});

// API: Auto-match a FIT file to a Strava activity by start time
app.get('/api/activity/:id/auto-fit', async (req, res) => {
  const folder = getFitFolder();
  if (!folder) {
    return res.json({ has_gear_data: false, source: 'fit_library', error: 'FIT library not configured' });
  }

  // Get activity start time from query param or fetch from Strava
  let startTime = req.query.start_date;

  if (!startTime) {
    // Fetch from Strava
    const token = await ensureValidToken(req);
    if (!token) return res.status(401).json({ error: 'Not authenticated' });

    try {
      const api = stravaApi(token);
      const resp = await api.get(`/activities/${req.params.id}`);
      startTime = resp.data.start_date;
    } catch (err) {
      return res.json({ has_gear_data: false, source: 'fit_library', error: 'Failed to fetch activity' });
    }
  }

  // Force rescan (quiet mode) so newly-downloaded files are picked up
  fitLibraryCache.scannedAt = 0;
  const match = findMatchingFit(startTime);
  if (!match) {
    return res.json({
      has_gear_data: false,
      source: 'fit_library',
      error: 'No matching FIT file found for this activity'
    });
  }

  console.log(`[FIT Library] Matched activity ${req.params.id} → ${path.basename(match.path)}`);

  // Parse the matched FIT file
  try {
    const fileBuffer = fs.readFileSync(match.path);
    const fitParser = new FitParser({
      force: true,
      speedUnit: 'km/h',
      lengthUnit: 'km',
      temperatureUnit: 'celsius',
      elapsedRecordField: true,
      mode: 'both'
    });

    fitParser.parse(fileBuffer, (error, data) => {
      if (error) {
        return res.json({ has_gear_data: false, source: 'fit_library', error: 'Failed to parse FIT file' });
      }

      const result = extractDi2Data(data);
      result.source = 'fit_library';
      result.matched_file = path.basename(match.path);

      // Auto-delete the FIT file if it's in the default download folder
      // (not in a user-configured library folder — those are intentionally kept)
      const defaultDl = getDefaultDownloadFolder();
      const configuredFolder = (process.env.FIT_FOLDER || '').trim();
      const fileDir = path.dirname(match.path);
      if (result.has_gear_data && defaultDl && !configuredFolder && fileDir === defaultDl) {
        try {
          fs.unlinkSync(match.path);
          console.log(`[FIT Library] Auto-deleted downloaded FIT: ${path.basename(match.path)}`);
          result.auto_deleted = true;
          // Invalidate cache since we deleted a file
          fitLibraryCache.scannedAt = 0;
        } catch (delErr) {
          console.warn(`[FIT Library] Could not auto-delete ${path.basename(match.path)}: ${delErr.message}`);
        }
      }

      res.json(result);
    });
  } catch (err) {
    console.error('[FIT Library] Parse error:', err.message);
    res.json({ has_gear_data: false, source: 'fit_library', error: 'Failed to read FIT file' });
  }
});

// API: Rescan FIT library (force cache invalidation)
app.post('/api/fit-library/rescan', (req, res) => {
  fitLibraryCache = { folder: null, files: [], scannedAt: 0 };
  const files = scanFitLibrary();
  res.json({ fileCount: files.length });
});

// ─── Setup Page HTML ────────────────────────────────────────────────────────

function getSetupPageHtml() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Setup — Di2va</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap">
  <style>
    :root {
      --bg: #0f1117; --bg-card: #1a1d27; --border: #2a2d3a;
      --text: #e4e4e7; --text-muted: #8b8fa3; --accent: #fc4c02;
      --accent-hover: #e04400; --blue: #3b82f6; --green: #22c55e;
      --radius: 8px; --font: 'Inter', -apple-system, sans-serif;
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: var(--font); background: var(--bg); color: var(--text);
           display: flex; align-items: center; justify-content: center;
           min-height: 100vh; padding: 24px; -webkit-font-smoothing: antialiased; }
    .card { background: var(--bg-card); border: 1px solid var(--border);
            border-radius: 16px; padding: 40px; max-width: 520px; width: 100%; }
    .logo { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
    .logo svg { width: 32px; height: 32px; color: var(--accent); }
    .logo h1 { font-size: 1.3rem; font-weight: 700; letter-spacing: -0.02em; }
    .subtitle { color: var(--text-muted); margin-bottom: 28px; font-size: 0.95rem; line-height: 1.5; }
    .steps { background: rgba(59,130,246,0.08); border: 1px solid rgba(59,130,246,0.2);
             border-radius: var(--radius); padding: 16px 20px; margin-bottom: 28px; font-size: 0.85rem; }
    .steps h3 { color: var(--blue); font-size: 0.8rem; text-transform: uppercase;
                letter-spacing: 0.06em; margin-bottom: 8px; }
    .steps ol { padding-left: 18px; color: var(--text-muted); }
    .steps ol li { margin-bottom: 4px; }
    .steps a { color: var(--blue); text-decoration: underline; }
    label { display: block; font-size: 0.8rem; font-weight: 600;
            text-transform: uppercase; letter-spacing: 0.04em;
            color: var(--text-muted); margin-bottom: 6px; margin-top: 18px; }
    label:first-of-type { margin-top: 0; }
    input[type="text"], input[type="password"] {
      width: 100%; padding: 10px 14px; background: var(--bg);
      border: 1px solid var(--border); border-radius: var(--radius);
      color: var(--text); font-family: var(--font); font-size: 0.95rem;
      outline: none; transition: border-color 0.15s; }
    input:focus { border-color: var(--accent); }
    .hint { font-size: 0.75rem; color: var(--text-muted); margin-top: 4px; }
    button { display: block; width: 100%; margin-top: 28px; padding: 12px;
             background: var(--accent); color: #fff; border: none;
             border-radius: var(--radius); font-family: var(--font);
             font-size: 1rem; font-weight: 600; cursor: pointer;
             transition: background 0.15s; }
    button:hover { background: var(--accent-hover); }
    .footer { text-align: center; margin-top: 16px; font-size: 0.75rem; color: var(--text-muted); }
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="5" cy="18" r="3"/><circle cx="19" cy="18" r="3"/>
        <path d="M5 18l4-8 4 4 6-10"/>
      </svg>
      <h1>Di2va</h1>
    </div>
    <p class="subtitle">Welcome! To get started, connect your Strava API application. This only takes a minute.</p>

    <div class="steps">
      <h3>Before you begin</h3>
      <ol>
        <li>Go to <a href="https://www.strava.com/settings/api" target="_blank">strava.com/settings/api</a></li>
        <li>Create an application (Category: <strong>Visualizer</strong>)</li>
        <li>Set <strong>Authorization Callback Domain</strong> to <code>localhost</code></li>
        <li>Copy your <strong>Client ID</strong> and <strong>Client Secret</strong> below</li>
      </ol>
    </div>

    <form method="POST" action="/setup">
      <label for="client_id">Strava Client ID</label>
      <input type="text" id="client_id" name="client_id" placeholder="e.g. 12345" required autofocus>

      <label for="client_secret">Strava Client Secret</label>
      <input type="password" id="client_secret" name="client_secret" placeholder="e.g. abc123def456..." required>

      <label for="session_secret">Session Secret <span style="font-weight:400;text-transform:none">(optional)</span></label>
      <input type="text" id="session_secret" name="session_secret" placeholder="Auto-generated if left blank">
      <p class="hint">A random string used to sign session cookies. Leave blank to auto-generate.</p>

      <button type="submit">Save &amp; Connect to Strava →</button>
    </form>
    <p class="footer">Credentials are saved to <code>.env.local</code> which is gitignored and never committed.</p>
  </div>
</body>
</html>`;
}

// ─── Start Server ───────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`\n🚴 Di2va running at http://localhost:${PORT}`);

  if (!isStravaConfigured()) {
    console.log(`\n  ⚡ First-time setup required!`);
    console.log(`  → Open http://localhost:${PORT}/setup to configure your Strava API credentials\n`);
  } else {
    console.log(`  ✅ Strava API configured`);
  }

  const fitFolder = getFitFolder();
  if (fitFolder) {
    const files = scanFitLibrary();
    console.log(`  📂 FIT Library: ${fitFolder} (${files.length} files indexed)\n`);
  } else {
    console.log(`  📂 FIT Library: not configured — set via Settings in the app\n`);
  }
});
